# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email2',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name2',
            field=models.TextField(default='', verbose_name=''),
            preserve_default=False,
        ),
    ]
